name: streamlit-app
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      # dev
      - -e .
      - pylint
      - rich
      - ruff
      # base
      - streamlit
      - watchdog
      # specific
      - python-dotenv

